language: python
python:
- '3.5'

sudo: required
dist: trusty

install:
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-context
- pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards
addons:
  apt_packages:
  - pandoc
script: bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: b6a4c68c1fcb
  - COMMIT_AUTHOR_EMAIL: florian.akos.szabo@gmail.com

